
# Base Settings
title = "Coaching | Strooware Interactive"
baseURL = "https://strooware.nl"

# Theme Settings
theme = "strooware"

# Language Settings
defaultContentLanguage = "nl"

# Params
[[params.footer.extra]]
text = "KvK 75604442"
[[params.footer.extra]]
text = "Btw NL002240901B10"
[[params.footer.extra]]
text = "IBAN NL16 KNAB 0259 4681 18"
