apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: tst-

resources:
  - ../../base

patches:
  - patch: |-
      - { op: replace, path: /spec/rules/0/host, value: tst.strooware.nl }
      - { op: replace, path: /spec/tls/0/hosts/0, value: tst.strooware.nl }
      - { op: replace, path: /spec/tls/0/secretName, value: tst-website-strooware-certs }
    target: { kind: Ingress }
