apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: tst-
namespace: strooware

resources:
  - ../../base

patches:
  - patch: |-
      - { op: replace, path: /spec/rules/0/host, value: tst.strooware.nl }
    target: { kind: Ingress }
