apiVersion: apps/v1
kind: Deployment

metadata:
  name: website-strooware

spec:
  replicas: 1
  revisionHistoryLimit: 1

  template:
    spec:
      containers:
        - name: website-strooware
          image: docker.io/strootje/strooware:1
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 80
              protocol: TCP

      serviceAccountName: website-strooware
