apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: website-strooware
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: acme-letsencrypt-production

spec:
  rules:
    - host: strooware.nl
      http:
        paths:
          - path: /
            backend:
              service:
                name: website-strooware
                port:
                  name: http
            pathType: Prefix
  tls:
    - hosts:
        - strooware.nl
      secretName: prd-website-strooware-certs
  ingressClassName: traefik
