apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: website-strooware
  app.kubernetes.io/version: 1.0.0

resources:
  - service.yml
  - service-account.yml
  - deployment.yml
  - ingress.yml
